%YAML:1.0

# Project
project_name: "lvi_sam"

#common parameters
imu_topic: "/os1_cloud_node/imu"
image_topic: "/camera/image_color"
point_cloud_topic: "lvi_sam/lidar/deskew/cloud_deskewed"

# Lidar Params
use_lidar: 1                     # whether use depth info from lidar or not
lidar_skip: 3                    # skip this amount of scans
align_camera_lidar_estimation: 0 # align camera and lidar estimation for visualization

# lidar to camera extrinsic (YPR = ZYX)
lidar_to_cam_tx: -0.395118861616406
lidar_to_cam_ty: -0.287847080789597
lidar_to_cam_tz: -0.121733085070471
lidar_to_cam_rx: -1.6036708
lidar_to_cam_ry: 0.0009031
lidar_to_cam_rz:  1.5811758

# lidar to imu extrinsic 
lidar_to_imu_tx: 0.006253
lidar_to_imu_ty: -0.011775
lidar_to_imu_tz: 0.028535
lidar_to_imu_rx: 0.0
lidar_to_imu_ry: 0.0
lidar_to_imu_rz: 3.1415927

# camera model (new camera)
model_type: PINHOLE
camera_name: camera

# Mono camera config
image_width: 1280
image_height: 1024
distortion_parameters:
   k1: 0.5424763304847061
   k2: -1.7515099175022195
   p1: 6.050489512760127
   p2: -5.786170959900578
projection_parameters:
   fx: 702.6030497884977
   fy: 703.4541726858521
   cx: 644.9296487349911
   cy: 526.4572414665469


#imu parameters       The more accurate parameters you provide, the worse performance
acc_n: 0.08         # accelerometer measurement noise standard deviation.
gyr_n: 0.04         # gyroscope measurement noise standard deviation.
acc_w: 0.00004        # accelerometer bias random work noise standard deviation.
gyr_w: 2.0e-6       # gyroscope bias random work noise standard deviation.
g_norm: 9.81007       #

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning. 
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ -0.9999,   -0.0130,   -0.0046,
            0.0047,   -0.0125,   -0.9999,   
            0.0129,   -0.9998,    0.0125]

#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.0242, -0.1850,  -0.4121] 

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 7            # min distance between two features 
freq: 0                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04   # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0  # keyframe selection threshold (pixel)

#unsynchronization parameters
estimate_td: 0           # online estimate time offset between camera and imu
td: 0                    # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0       # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0    # unit: s. rolling shutter read out time per frame (from data sheet). 

#loop closure parameters
loop_closure: 1                    # start loop closure
skip_time: 0.0
skip_dist: 0.0
debug_image: 0                      # save raw image in loop detector for visualization prupose; you can close this function by setting 0 
match_image_scale: 0.5
vocabulary_file: "/config/brief_k10L6.bin"
brief_pattern_file: "/config/brief_pattern.yml"